# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-11 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='mobilephone',
            new_name='mobile_phone',
        ),
    ]
