# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-11 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210411_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='emai',
            field=models.EmailField(db_index=True, max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_index=True, max_length=32, verbose_name='用户名'),
        ),
    ]
