# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pricepolicy_project_projectuser_transation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (2, '收费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='project_space',
            field=models.PositiveIntegerField(verbose_name='项目空间（G）'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(3, '#11EE11'), (2, '#EEEE11'), (6, '#11EEEE'), (5, '#C211EE'), (1, '#F70909'), (7, '#96EE11'), (4, '#113DEE')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='emai',
            field=models.EmailField(db_index=True, max_length=32, null=True, verbose_name='邮箱'),
        ),
    ]
