# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-15 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210414_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transation',
            old_name='project_policy',
            new_name='price_policy',
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(3, '#11EE11'), (6, '#11EEEE'), (2, '#EEEE11'), (1, '#F70909'), (7, '#96EE11'), (4, '#113DEE'), (5, '#C211EE')], default=1, verbose_name='颜色'),
        ),
    ]
