# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210415_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='项目')),
                ('content', models.TextField(verbose_name='内容')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Wiki', verbose_name='所属目录')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#F70909'), (2, '#EEEE11'), (5, '#C211EE'), (6, '#11EEEE'), (3, '#11EE11'), (7, '#96EE11'), (4, '#113DEE')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transation',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已支付'), (0, '未支付')], verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='wiki',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='项目'),
        ),
    ]
