# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210417_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(3, '其他'), (2, '收费版'), (1, '免费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(2, '#EEEE11'), (6, '#11EEEE'), (3, '#11EE11'), (4, '#113DEE'), (1, '#F70909'), (7, '#96EE11'), (5, '#C211EE')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.Wiki', verbose_name='所属目录'),
        ),
    ]
