# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-17 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210417_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(2, '收费版'), (3, '其他'), (1, '免费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(5, '#C211EE'), (6, '#11EEEE'), (4, '#113DEE'), (1, '#F70909'), (2, '#EEEE11'), (7, '#96EE11'), (3, '#11EE11')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='title',
            field=models.CharField(max_length=128, verbose_name='项目'),
        ),
    ]
