# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-18 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20210417_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='目录级别'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(3, '其他'), (2, '收费版'), (1, '免费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(6, '#11EEEE'), (7, '#96EE11'), (3, '#11EE11'), (2, '#EEEE11'), (1, '#F70909'), (4, '#113DEE'), (5, '#C211EE')], default=1, verbose_name='颜色'),
        ),
    ]
