# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20210418_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (2, '收费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(5, '#C211EE'), (6, '#11EEEE'), (3, '#11EE11'), (2, '#EEEE11'), (4, '#113DEE'), (7, '#96EE11'), (1, '#F70909')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transation',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已支付'), (0, '未支付')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='目录级别'),
        ),
    ]
