# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210418_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default='cos', max_length=128, verbose_name='COS桶'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(2, '收费版'), (1, '免费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(5, '#C211EE'), (7, '#96EE11'), (3, '#11EE11'), (6, '#11EEEE'), (4, '#113DEE'), (2, '#EEEE11'), (1, '#F70909')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], verbose_name='状态'),
        ),
    ]
