# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210418_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='cos0', max_length=128, verbose_name='COS桶区域'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(2, '收费版'), (3, '其他'), (1, '免费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(3, '#11EE11'), (2, '#EEEE11'), (1, '#F70909'), (7, '#96EE11'), (5, '#C211EE'), (6, '#11EEEE'), (4, '#113DEE')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transation',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已支付'), (0, '未支付')], verbose_name='状态'),
        ),
    ]
