# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-20 15:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210418_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='文件/文件夹名', max_length=64, verbose_name='文件名')),
                ('type', models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='类型')),
                ('key', models.CharField(blank=True, max_length=128, null=True, verbose_name='cos存储关键字')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('file_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='路径')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='web.File', verbose_name='上级目录')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='header_img',
            field=models.CharField(default='none', max_length=128, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=16, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default='2021-04-15 01:47:48.282870', verbose_name='注册时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(2, 'female'), (1, 'male'), (0, '性别隐藏')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(3, '其他'), (2, '收费版'), (1, '免费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(2, '#EEEE11'), (4, '#113DEE'), (5, '#C211EE'), (7, '#96EE11'), (3, '#11EE11'), (1, '#F70909'), (6, '#11EEEE')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_index=True, max_length=32, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{1}[0-9a-zA-Z]*$', '账号必须以字母开头，后由数字字母组成')], verbose_name='账号'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='file',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Userinfo', verbose_name='更新者'),
        ),
    ]
