# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210420_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='web.File', verbose_name='上级目录'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.SmallIntegerField(choices=[(2, '文件夹'), (1, '文件')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (3, '其他'), (2, '收费版')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(4, '#113DEE'), (5, '#C211EE'), (3, '#11EE11'), (2, '#EEEE11'), (7, '#96EE11'), (1, '#F70909'), (6, '#11EEEE')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, 'male'), (0, '性别隐藏'), (2, 'female')], default=0, verbose_name='性别'),
        ),
    ]
