# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-25 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210421_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='adress',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(2, '收费版'), (1, '免费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='per_file_size',
            field=models.PositiveIntegerField(help_text='M', verbose_name='单文件上传大小（M）'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='project_space',
            field=models.PositiveIntegerField(help_text='G', verbose_name='单项目空间（G）'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(3, '#11EE11'), (4, '#113DEE'), (2, '#EEEE11'), (1, '#F70909'), (5, '#C211EE'), (6, '#11EEEE'), (7, '#96EE11')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='transation',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已支付'), (0, '未支付')], verbose_name='状态'),
        ),
    ]
