# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20210425_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (2, '收费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(5, '#C211EE'), (7, '#96EE11'), (2, '#EEEE11'), (6, '#11EEEE'), (3, '#11EE11'), (4, '#113DEE'), (1, '#F70909')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '性别隐藏'), (2, '女'), (1, '男')], default=0, verbose_name='性别'),
        ),
    ]
