# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-04-29 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210427_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.SmallIntegerField(choices=[(2, '文件夹'), (1, '文件')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='issuesreply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.IssuesReply', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='issuesreply',
            name='reply_type',
            field=models.IntegerField(choices=[(1, '修改记录'), (2, '评论')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版'), (2, '收费版'), (3, '其他')], default=2, verbose_name='收费类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#F70909'), (2, '#EEEE11'), (5, '#C211EE'), (3, '#11EE11'), (4, '#113DEE'), (7, '#96EE11'), (6, '#11EEEE')], default=1, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '不填'), (2, '女'), (1, '男')], default=0, verbose_name='性别'),
        ),
    ]
